# Generated by Django 5.1.15 on 2026-04-12 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceSignal",
            fields=[
                (
                    "attendance_signal_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("driver_id", models.UUIDField()),
                ("attendance_date", models.DateField()),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("dispatch", "dispatch")],
                        default="dispatch",
                        max_length=32,
                    ),
                ),
                (
                    "suggested_status",
                    models.CharField(
                        choices=[
                            ("worked", "worked"),
                            ("day_off", "day_off"),
                            ("exception", "exception"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "raw_reason_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("source_reference", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("attendance_date", "driver_id", "source_reference"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_kind", "source_reference"),
                        name="unique_attendance_signal_per_source_reference",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                (
                    "attendance_day_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("driver_id", models.UUIDField()),
                ("attendance_date", models.DateField()),
                (
                    "final_status",
                    models.CharField(
                        choices=[
                            ("worked", "worked"),
                            ("day_off", "day_off"),
                            ("exception", "exception"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "decided_source_kind",
                    models.CharField(default="dispatch", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_signal",
                    models.ForeignKey(
                        blank=True,
                        db_column="decided_signal_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_days",
                        to="attendanceregistry.attendancesignal",
                    ),
                ),
            ],
            options={
                "ordering": ("attendance_date", "driver_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("driver_id", "attendance_date"),
                        name="unique_attendance_day_per_driver_date",
                    )
                ],
            },
        ),
    ]
